# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RealEstateRegression
                                 A QGIS plugin
 Plugin to execute regression for real estate
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-27
        copyright            : (C) 2019 by Thorsten Kelm, Hochschule Bochum
        email                : thorsten.kelm@hs-bochum.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RealEstateRegression class from file RealEstateRegression.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .real_estate_regression import RealEstateRegression
    return RealEstateRegression(iface)
